### ISSUE TITLE
Add a Big Data SIG to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#272]
proposed url: http://commons.openshift.org/sig/OpenshiftBigData.html

links added to http://commons.openshift.org/index.html#interests section of home page

update google spreadsheet-based form to start collecting email addresses

@jiri-fiala @jsvgoncalves

Form/Style should mirror the existing SIG page /sig/Openshiftv3.html

Content for link on index.html:
'OpenShift Big Data’

Content for beneath link on #interests section of index.html

'Discuss, develop and disseminate best practices for working with Big Data on OpenShift'

Content for http://commons.openshift.org/sig/OpenshiftBigData.html

'Join the OpenShift Big Data Special Interest Group'

1. Cut the section of the page entitled 'OpenShift 3 Commons Briefings' on the .edu sig landing page.
2. Copy the section of the page entitled 'OpenShift 3 Articles' onto the Big Data sig landing page.
3. Add this blog post as the first ‘article’ listed in the ‘OpenShift 3 Articles’ section:
        https://blog.openshift.com/running-analytics-openshift-daikon/

**Comment by jiri-fiala** [comment]
Rather than hard-coding a single blog article to the RSS feed of v3 blog articles, I have listed all the "big-data" tagged articles (currently two of them, including the [Running Analytics on OpenShift with Daikon](https://blog.openshift.com/running-analytics-openshift-daikon/); supposedly they will grow in numbers over time).
Other than the mentioned change, it's according to the spec [above](https://github.com/openshift/commons.openshift.org/issues/272#issue-154354973), prepared in [this commit](https://github.com/jiri-fiala/commons.openshift.org/commit/060f52631fb90307dd7f2b9c0acfbdef79471d5e).

@dmueller2001, please review the [**index** page](http://comm-jfiala.rhcloud.com/index.html#interests) & the [**form**](http://comm-jfiala.rhcloud.com/sig/OpenshiftBigData.html) and approve.

**Comment by dmueller2001** [comment]
IN the header on the Big Data landing page: 

Change the following:

"OpenShift 3
The principal purpose of the OpenShift 3 Special Interest Group is to collaborate and discuss items for the OpenShift 3 platform."

to

"Big Data on OpenShift
The principal purpose of the Big Data Special Interest Group is to discuss, develop and disseminate best practices for working with Big Data and Big Data tool chains on OpenShift"

Sorry @jiri-fiala I missed the header changes

**Comment by jiri-fiala** [comment]
@dmueller2001, I missed that one too, it's [corrected](https://github.com/jiri-fiala/commons.openshift.org/commit/766ab293b96e64192eb7dc1f7065df66ffb10dfb) now. It can be previewed [here](http://comm-jfiala.rhcloud.com/sig/OpenshiftBigData.html). If everything's OK, I'll make a PR.

**Comment by dmueller2001** [comment]
Looks good, please make the PR asap and rebuild ASAP ;-) many thanks!



On Mon, May 16, 2016 at 7:05 AM, Jiri Fiala <notifications@github.com>
wrote:

> @dmueller2001 <https://github.com/dmueller2001>, I missed that one too,
> it's corrected
> <https://github.com/jiri-fiala/commons.openshift.org/commit/766ab293b96e64192eb7dc1f7065df66ffb10dfb>
> now. It can be previewed here
> <http://comm-jfiala.rhcloud.com/sig/OpenshiftBigData.html>. If
> everything's OK, I'll make a PR.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/commons.openshift.org/issues/272#issuecomment-219433276>
>



-- 
Kind Regards,

Diane Mueller
Director, Community Development
Red Hat OpenShift
@openshiftcommons

We have more in Common than you know, learn more at
http://commons.openshift.org
