### ISSUE TITLE
Update Briefings videos to match Gathering videos styling

### ISSUE THREAD

**Issue by wgordon17** [openshift/commons.openshift.org#361]
Request by Jorge Morales to update the video section of http://commons.openshift.org/briefings.html to match the stying of http://commons.openshift.org/videos.html, as both of these videos are key to OpenShift promotion

**Comment by wgordon17** [comment]
@dmueller2001 

"list (in LIFO) the 10 most recent briefings and SIG videos from youtube channel in the bottom half of the briefings.html page and remove the out-of-date older list of videos"

**Comment by wgordon17** [comment]
Please review http://commons-wgordon-test.44fs.preview.openshiftapps.com/briefings.html before I push this live

**Comment by dmueller2001** [comment]
That looks nice, does it self update or will we need to update it each week
as new recordings get added to YouTube channel?

D

**Comment by wgordon17** [comment]
Both briefings videos and gatherings videos are stored in a static list, e.g., https://github.com/openshift/commons.openshift.org/blob/master/data/videos.yml. Updates to both video lists should be provided in the form of a GH issue.

Do you intend to **only** have 10 Briefings videos at a time?

**Comment by wgordon17** [comment]
The biggest reason for the static list is due to lack of information available from Youtube. The list allows us to provide a truncated title, author section, and one line description.

**Comment by wgordon17** [comment]
Looking at the Youtube uploading information for videos, I just can't seem to find a good place to load that information in from. So, although I really like the idea of dynamically updating, it may degrade the quality of information we're able to provide on the commons site itself

**Comment by dmueller2001** [comment]
I can update the .Yml file each week manually

D

On Jan 13, 2017 12:54 PM, "Will Gordon" <notifications@github.com> wrote:

Looking at the Youtube uploading information for videos, I just can't seem
to find a good place to load that information in from. So, although I
really like the idea of dynamically updating, it may degrade the quality of
information we're able to provide on the commons site itself

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/commons.openshift.org/issues/361#issuecomment-272545444>,
or mute the thread
