### ISSUE TITLE
Update Dynatrace logo

### ISSUE THREAD

**Issue by fraka79** [openshift/commons.openshift.org#419]
Can you please update the Dynatrace logo - the quality is very poor and can not be used for bigger banners.
Attached a logo with a higher resolution
![dynatrace_logo_rgb_cpv_2048x2048px](https://cloud.githubusercontent.com/assets/26711197/25899121/f032ab5c-358e-11e7-9419-f7c38cb7f130.png)

**Comment by jsvgoncalves** [comment]
I'm not sure why (or whence) this request comes from, but please check the [contributing](https://github.com/openshift/commons.openshift.org/blob/master/CONTRIBUTING.md#adding-partners) guidelines for this repository, in specific:

> Resize it to a reasonable dimension, default to 120px width and variable height.

We want to reduce the page load and therefore are not interested in serving high quality images nor in using our website as sort of a CDN for any kind of logos.

**Comment by fraka79** [comment]
upload / change request came from Diane Mueller  / Director of Community Development during our discussion at last weeks RedHat summit

**Comment by jsvgoncalves** [comment]
@dmueller2001 I can not verify this, can you please step in?

**Comment by jsvgoncalves** [comment]
I'm temporarily reopening this until we get feedback from @dmueller2001 .

**Comment by dmueller2001** [comment]
@jsvgoncalves yes I confirm that the @fraka79 request/issue is legitimate and you should update their logo

**Comment by jsvgoncalves** [comment]
@dmueller2001 There's no way we want to have the commons page load such a high resolution logo only to then resize it to a tiny `64-120 px` . Specially for mobile phones this is absolutely horrifying. In any case, there's already work in progress for us to start serving a spritesheet to boost page loading times which makes this even more impossible. 

Given this, what we can do is host the image separately on another location but still use the compressed one for the commons page. Still, I am not sure whether we have property rights over the image, specially to redistribute it, other than to use it on our commons page?

**Comment by luciddreamz** [comment]
The Dynatrace logo on this page isn't intended to be used for larger banners - it's intended to be used on this page only. If you need a version for larger banners, please visit: https://www.dynatrace.com/company/press-kit/

**Comment by dmueller2001** [comment]
Understood. Close the issue and I will contact dynatrace.

On May 10, 2017 9:58 AM, "João Gonçalves" <notifications@github.com> wrote:

@dmueller2001 <https://github.com/dmueller2001> There's no way we want to
have the commons page load such a high resolution logo only to then resize
it to a tiny 64-120 px . Specially for mobile phones this is absolutely
horrifying. In any case, there's already work in progress for us to start
serving a spritesheet to boost page loading times which makes this even
more impossible.

Given this, what we can do is host the image separately on another location
but still use the compressed one for the commons page. Still, I am not sure
whether we have property rights over the image, specially to redistribute
it, other than to use it on our commons page?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/commons.openshift.org/issues/419#issuecomment-300490219>,
or mute the thread
