### ISSUE TITLE
Time.ly calendar not showing on events.html page

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#463]
The time.ly widget for the calendar is not embedded correctly. IMHO this has to do  the https vs. http link that is in the embed code snippet as there's a warning to check if a site's connection is secure 
![screen shot 2017-06-29 at 12 23 31 pm](https://user-images.githubusercontent.com/4029488/27706422-60eea81a-5cc6-11e7-84b5-fa0b630d004e.png)

The direct link for the calendar is here:  https://live-timely-objzoywz.time.ly/ so I know the calendar is working
 @wgordon17 @jiri-fiala

**Comment by wgordon17** [comment]
With just the "//" it loads it with whatever the page is being served on...so on http://commons it serves from http...and on https://commons it serves from https...but the script itself, on timely's side needs to be fixed

![screen shot 2017-06-29 at 15 55 48](https://user-images.githubusercontent.com/22222756/27709126-fd98c67e-5ce8-11e7-901a-b80b0cd57375.png)
At the *very* least, that line needs to be fixed to call http or https depending on the page


![111](https://user-images.githubusercontent.com/22222756/27709147-0d5c0490-5ce9-11e7-84cf-a4cc7896b478.png)
But they also call all of these scripts over http only, instead of https....so they're script is definitely not setup for serving over https

**Comment by wgordon17** [comment]
Resolved by the timely team
